config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
		collection do
			post :import
      get 'remove_all'
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	def self.import(file)
    counter = 0
		CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
			contact = Contact.assign_from_row(row)
      if contact.save
        counter += 1
      else
        puts "#{contact.name} - #{contact.errors.full_messages.jion(",")}"
      end
		end
    counter
	end

	def self.assign_from_row(row)
    contact = Contact.where(name: row[:name]).first_or_initialize
    contact.assign_attributes row.to_hash
    contact
  end
	# def self.open_spreadsheet(file)
	# 	case File.extname(file.original_filename)
	# 		when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
	# 		when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	# 		when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	# 		else raise "Unknown file type: #{file.original_filename}"
	# 	end
	# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
		respond_to do |format|
			format.html
			format.csv { send_data @contacts.to_csv }
		end
  end
  def remove_all
    Contact.delete_all
    flash[:notice] = "You have removed all contacts!"
    redirect_to root_path
  end

	def import
		count = Contact.import params[:file]
		redirect_to home_index_path, notice: "Contacts #{count} imported."
	end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contacts = Contact.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the current layout name. Allows asserting the rendered layout name
  # in our feature specs as an alternative to the deprecated #render_template

  # Select the appropriate Boostrap class for Rails's flash messages
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'   # Green
    when 'error'
      'alert-danger'    # Red
    when 'alert'
      'alert-warning'   # Yellow
    else
      'alert-info'      # Blue
    end
  end

  # Display model validation errors in form templates
  def display_validation_errors(object)
    return '' if object.errors.empty?

    header = I18n.t('activerecord.errors.template.header',
                    count: object.errors.count)
    msgs = object.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
      <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <h4>
          #{header}
        </h4>
        <ul>#{msgs}</ul>
      </div>
    HTML

    html.html_safe
  end
end

app/views/contacts/_form.html.haml
= simple_form_for(@contact) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :phone

  .form-actions
    = f.button :submit

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
.text-center
  %h3 Importing Contacts
.jumbotron.text-center
  = form_tag import_contacts_path, multipart: true do
    .text-center
      = file_field_tag :file
    = submit_tag "Import", class: "btn btn-primary"

.text-center
  = link_to "Remove All #{@contacts.count}", remove_all_contacts_path, :method => :get , class: "btn btn-danger"

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @contact.name
%p
  %b Phone:
  = @contact.phone

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

app/views/home/index.html.haml
%ul#selector
  - @contacts.each do |contact|
    %li
      = contact.name

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', :type => 'button'} &times;
      = content_tag :div, msg, :id => 'flash_#{name}'

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-expanded' => 'false', 'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => '/'} Wedding Contact
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to home_index_path do
            Contact
            %span.sr-only (current)
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => '#'} Action
            %li
              %a{:href => '#'} Another action
            %li
              %a{:href => '#'} Something else here
            %li.divider{:role => 'separator'}
            %li
              %a{:href => '#'} Separated link

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ContactUpload
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = stylesheet_link_tag "print", media: 'print'

  %body{ id: "#{controller_name}_#{params[:action]}" }
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield